// Day21/A2ui/a2ui/renderers/angular/src/v0_8/components/checkbox.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Types } from '../types';

@Component({
  selector: 'a2ui-checkbox',
  template: `
    <label>
      <input
        type="checkbox"
        [id]="inputId"
        [checked]="inputChecked()"
        (change)="onToggle($event)"
      />
      {{ resolvedLabel() }}
    </label>
  `,
  styles: `
    :host {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Checkbox extends DynamicComponent<Types.CheckboxNode> {
  readonly label = input.required<Types.StringValue | null>();
  readonly checked = input.required<Types.BooleanValue | null>();

  protected inputChecked = computed(() => super.resolvePrimitive(this.checked()) ?? false);
  protected resolvedLabel = computed(() => super.resolvePrimitive(this.label()));
  protected readonly inputId = super.getUniqueId('a2ui-checkbox');

  onToggle(event: Event) {
    const checked = (event.target as HTMLInputElement).checked;
    this.sendAction({
      name: 'toggle',
      context: [{ key: 'checked', value: { literalBoolean: checked } }],
    });
  }
}

// Day21/A2ui/a2ui/renderers/react/src/v0_9/catalog/basic/components/CheckBox.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {createReactComponent} from '../../../adapter';
import {CheckBoxApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {LEAF_MARGIN} from '../utils';

export const CheckBox = createReactComponent(CheckBoxApi, ({props}) => {
  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    props.setValue(e.target.checked);
  };

  const uniqueId = React.useId();

  const hasError = props.validationErrors && props.validationErrors.length > 0;

  return (
    <div style={{display: 'flex', flexDirection: 'column', margin: LEAF_MARGIN}}>
      <div style={{display: 'flex', alignItems: 'center', gap: '8px'}}>
        <input
          id={uniqueId}
          type="checkbox"
          checked={!!props.value}
          onChange={onChange}
          style={{cursor: 'pointer', outline: hasError ? '1px solid red' : 'none'}}
        />
        {props.label && (
          <label
            htmlFor={uniqueId}
            style={{cursor: 'pointer', color: hasError ? 'red' : 'inherit'}}
          >
            {props.label}
          </label>
        )}
      </div>
      {hasError && (
        <span style={{fontSize: '12px', color: 'red', marginTop: '4px'}}>
          {props.validationErrors[0]}
        </span>
      )}
    </div>
  );
});
